"""
===========================================================
 Project:   SensorCalibration
 Generated: 2026-02-19 09:05:34
===========================================================

Authors:
  • Tobias Madlberger (Scaffold / CLI Author)
  • RaccoonOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.
"""

from libstp import (
    Drive,
    FusedOdometry,
    FusedOdometryConfig,
    GenericRobot,
    MecanumKinematics,
    SensorPosition,
    UnifiedMotionPidConfig,
    WheelPosition,
)

from src.hardware.defs import Defs


from src.missions.setup_mission import SetupMission
from src.missions.shutdown_mission import ShutdownMission
from src.missions.potato_mission import PotatoMission


class Robot(GenericRobot):
    defs = Defs()
    kinematics = MecanumKinematics(
        back_left_motor=defs.rear_left_motor,
        back_right_motor=defs.rear_right_motor,
        front_left_motor=defs.front_left_motor,
        front_right_motor=defs.front_right_motor,
        max_acceleration=40.678,
        max_velocity=50.847,
        track_width=0.19,
        wheel_radius=0.0295,
        wheelbase=0.12,
    )
    odometry = FusedOdometry(
        imu=defs.imu, kinematics=kinematics, config=FusedOdometryConfig(bemf_trust=1.0)
    )
    motion_pid_config = UnifiedMotionPidConfig(
        distance={"kp": 2.0, "ki": 0.0, "kd": 0.0},
        heading={"kp": 1.0, "ki": 0.0, "kd": 0.0},
        lateral={"kp": 2.0, "ki": 0.0, "kd": 0.0},
        profile={"max_linear_acceleration": 1.0},
        integral_max=10.0,
        integral_deadband=0.01,
        derivative_lpf_alpha=0.5,
        output_min=-10.0,
        output_max=10.0,
        saturation={"derating_factor": 0.85, "min_scale": 0.1, "recovery_rate": 0.02},
        heading_saturation={
            "derating_factor": 0.85,
            "min_scale": 0.25,
            "recovery_rate": 0.05,
        },
        tolerances={"distance_m": 0.01, "angle_rad": 0.017},
        rate_limits={"max_heading_rate": 3.0, "min_angular_rate": 0.1},
        lateral_drift={
            "heading_bias_gain": 0.5,
            "reorient_threshold_m": 0.15,
            "heading_saturation_error_rad": 0.01,
            "heading_recovery_error_rad": 0.005,
        },
        min_speed_mps=0.05,
    )
    missions = [PotatoMission()]
    setup_mission = SetupMission()
    shutdown_mission = ShutdownMission()
    width_cm = 13.0
    length_cm = 19.0
    rotation_center_forward_cm = -1.5
    rotation_center_strafe_cm = 0.0
    _sensor_positions = {
        defs.front_left_ir_sensor: SensorPosition(
            forward_cm=7.5, strafe_cm=3.3, clearance_cm=1.0
        ),
        defs.front_right_ir_sensor: SensorPosition(
            forward_cm=7.5, strafe_cm=-3.3, clearance_cm=1.0
        ),
    }
    _wheel_positions = {
        defs.front_left_motor: WheelPosition(forward_cm=6.0, strafe_cm=9.5),
        defs.front_right_motor: WheelPosition(forward_cm=6.0, strafe_cm=-9.5),
        defs.rear_left_motor: WheelPosition(forward_cm=-6.0, strafe_cm=9.5),
        defs.rear_right_motor: WheelPosition(forward_cm=-6.0, strafe_cm=-9.5),
    }


__all__ = ["Robot"]
