"""Custom setup to build web IDE during pip install.

Environment variables:
    RACCOON_SKIP_WEBIDE: Set to skip web-ide build entirely (e.g., for server-only installs on Pi)
"""

import os
import shutil
import subprocess
import sys
from pathlib import Path

from setuptools import setup
from setuptools.command.build_py import build_py


ROOT_DIR = Path(__file__).parent

# --- Configurable version: x.y.BUILD_NUMBER ---
# CI sets BUILD_NUMBER=${{ github.run_number }}; local builds default to 0.
BASE_VERSION = "0.1"
BUILD_NUMBER = os.environ.get("BUILD_NUMBER", "0")
_computed_version = f"{BASE_VERSION}.{BUILD_NUMBER}"

_version_file = ROOT_DIR / "raccoon_cli" / "_version.py"
_version_file.write_text(
    f'"""Auto-generated by setup.py — do not edit manually."""\n\n'
    f'__version__ = "{_computed_version}"\n'
)


class WebIDEBuildError(Exception):
    """Raised when web-ide build fails."""

    pass


class BuildWithExtras(build_py):
    """Custom build command that builds the web IDE."""

    def run(self):
        # Skip web IDE build if explicitly requested (e.g., server-only install on Pi)
        if os.environ.get("RACCOON_SKIP_WEBIDE"):
            print("RACCOON_SKIP_WEBIDE set, skipping web IDE build")
            super().run()
            return

        root_dir = ROOT_DIR
        web_ide_dir = root_dir / "web-ide"
        dist_src = web_ide_dir / "dist" / "WebIDE" / "browser"
        dist_dest = root_dir / "raccoon_cli" / "web-ide-dist"

        # Check if web-ide directory exists
        if not web_ide_dir.exists():
            raise WebIDEBuildError(
                f"web-ide directory not found at {web_ide_dir}\n"
                "Set RACCOON_SKIP_WEBIDE=1 to skip web-ide build."
            )

        # Check for npm
        npm_cmd = shutil.which("npm")
        if not npm_cmd:
            raise WebIDEBuildError(
                "npm not found. Install Node.js to build web-ide.\n"
                "Set RACCOON_SKIP_WEBIDE=1 to skip web-ide build."
            )

        # Install npm dependencies (always run to keep node_modules in sync)
        print("Installing web IDE dependencies...")
        result = subprocess.run(
            [npm_cmd, "install"],
            cwd=web_ide_dir,
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            raise WebIDEBuildError(
                f"npm install failed:\n{result.stderr}\n"
                "Set RACCOON_SKIP_WEBIDE=1 to skip web-ide build."
            )

        # Build Angular app
        print("Building web IDE...")
        npx_cmd = shutil.which("npx")
        result = subprocess.run(
            [npx_cmd, "ng", "build", "--configuration=production"],
            cwd=web_ide_dir,
            capture_output=True,
            text=True,
        )
        if result.returncode != 0:
            error_output = result.stderr
            if result.stdout:
                error_output += f"\n{result.stdout}"
            raise WebIDEBuildError(
                f"ng build failed:\n{error_output}\n"
                "Set RACCOON_SKIP_WEBIDE=1 to skip web-ide build."
            )

        # Copy built files to package
        if dist_src.exists():
            print(f"Copying web IDE files to {dist_dest}")
            if dist_dest.exists():
                shutil.rmtree(dist_dest)
            shutil.copytree(dist_src, dist_dest)
        else:
            raise WebIDEBuildError(
                f"Build output not found at {dist_src}\n"
                "The Angular build may have failed silently.\n"
                "Set RACCOON_SKIP_WEBIDE=1 to skip web-ide build."
            )

        # Continue with normal build
        super().run()


setup(
    cmdclass={
        "build_py": BuildWithExtras,
    },
)
