"""
===========================================================
 Project:   tobi-test
 Generated: 2026-01-08 10:26:41
 Tool:      Raccoon IDE
 Platform:  StpOS – Robotics Operating System
===========================================================

Authors:
  • Tobias Madlberger (Scaffold Author)
  • StpOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.

Note: This header credits the scaffold and tooling only - no copyright is
claimed over the generated code itself.
"""
from libstp import seq, Mission
from libstp.step.drive import drive_forward
from libstp.step.turn import turn_cw


class PotatoMission(Mission):
    def sequence(self) -> "Step":
        return seq([
            drive_forward(cm=20),
            turn_cw(degrees=90)
        ])

