"""
===========================================================
 Project:   tobi-test
 Generated: 2026-01-08 10:26:41
 Tool:      Raccoon IDE
 Platform:  StpOS – Robotics Operating System
===========================================================

Authors:
  • Tobias Madlberger (Scaffold Author)
  • StpOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.

Note: This header credits the scaffold and tooling only - no copyright is
claimed over the generated code itself.
"""
import math

from libstp import seq, Mission, drive_forward, turn_left, Turn
from libstp.motion import TurnConfig
from libstp.step.motion import measure_max_angular_velocity
from libstp.step.motion import auto_tune_turn, motor_response_test

class PotatoMission(Mission):
    def sequence(self) -> "Step":
        return seq([
            turn_left(90),
            # auto_tune_turn(
            #     test_angle_deg=90.0,  # 90° test turns
            #     max_rate=1.0,  # your measured max
            #     gradient_steps=6,
            #     target_overshoot_deg=2.0,
            # )
            # measure_max_angular_velocity(duration=5.0, clockwise=False)
            # TuneTurn(angle=90),
            #turn_custom(90),
            # drive_forward(cm=15),
            # loop_forever(seq([
            #     open_drum_pusher(),
            #     #move_drum_motor_by_offset(-250),
            #     wait_for_button(),
            #     #wait_for_threshold(Defs.drum_distance_sensor),
            #     #wait(0.25),
            #     close_drum_pusher(),
            #     drum_retreat(),
            #     #wait_for_button(),
            # ])),
            #
            # open_drum_pusher(),
            # wait_for_checkpoint(11),
            # close_drum_pusher(),
            # drum_retreat(),
            #
            # open_drum_pusher(),
            # wait_for_checkpoint(10 + 8),
            # close_drum_pusher(),
            # drum_retreat(),
            #
            # open_drum_pusher(),
            # wait_for_checkpoint(10 + 7 + 8),
            # close_drum_pusher(),
            # drum_retreat(),
            #
            # open_drum_pusher(),
            # wait_for_checkpoint(10 + 7 + 7 + 8),
            # close_drum_pusher(),
            # drum_retreat(),
            #
            # open_drum_pusher(),
            # wait_for_checkpoint(10 + 7 + 7 + 7 + 8),
            # close_drum_pusher(),
            # drum_retreat(),
            #
            # open_drum_pusher(),
            # wait_for_checkpoint(10 + 7 + 7 + 7 + 7 + 8),
            # close_drum_pusher(),
            # drum_retreat(),
            #
            # open_drum_pusher(),
            # wait_for_checkpoint(10 + 7 + 7 + 7 + 7 + 7 + 8),
            # close_drum_pusher(),
            # drum_retreat(),
            #
            # open_drum_pusher(),
            # wait_for_checkpoint(10 + 7 + 7 + 7 + 7 + 7 + 7 + 8),
            # close_drum_pusher(),
            # drum_retreat(),

            # lineup(
            #     left_sensor=Defs.front_left_ir_sensor,
            #     right_sensor=Defs.front_right_ir_sensor,
            # ),

            # edge_lineup_on_black(
            #     left_sensor=Defs.front_left_ir_sensor,
            #     right_sensor=Defs.front_right_ir_sensor,
            # )
            # ReverseAlignOnEdge(
            #     left_sensor=Defs.front_left_ir_sensor,
            #     right_sensor=Defs.front_right_ir_sensor,
            # )
            # LineupUHH(left_sensor=Defs.front_left_ir_sensor, right_sensor=Defs.front_right_ir_sensor)
        ])
