"""
===========================================================
 Project:   tobi-test
 Generated: 2026-02-07 16:02:24
===========================================================

Authors:
  • Tobias Madlberger (Scaffold / CLI Author)
  • RaccoonOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.
"""

from libstp import (
    AnalogSensor,
    DigitalSensor,
    Feedforward,
    IRSensor,
    Motor,
    MotorCalibration,
    PidGains,
    Servo,
)
from src.hardware.thresholded_sensor import ThresholdedSensor
from libstp import IMU as Imu


class Defs:
    imu = Imu()
    button = DigitalSensor(port=10)
    front_left_motor = Motor(
        port=0,
        inverted=False,
        calibration=MotorCalibration(
            ff=Feedforward(kS=0.11, kV=0.1981503563639978, kA=0.02),
            pid=PidGains(kp=10.0, ki=9.814794609326363, kd=0.396417538966332),
            ticks_to_rad=0.004391830359802708,
            vel_lpf_alpha=0.8,
        ),
    )
    front_right_motor = Motor(
        port=1,
        inverted=False,
        calibration=MotorCalibration(
            ff=Feedforward(kS=0.09, kV=0.1350324603642087, kA=0.008225329011787715),
            pid=PidGains(kp=10.0, ki=10.0, kd=0.7032264861939415),
            ticks_to_rad=0.0042869081060705775,
            vel_lpf_alpha=0.8,
        ),
    )
    rear_left_motor = Motor(
        port=2,
        inverted=False,
        calibration=MotorCalibration(
            ff=Feedforward(kS=0.11, kV=0.18219958232362843, kA=0.02),
            pid=PidGains(kp=10.0, ki=10.0, kd=0.6018354462577499),
            ticks_to_rad=0.005058544093256774,
            vel_lpf_alpha=0.8,
        ),
    )
    rear_right_motor = Motor(
        port=3,
        inverted=False,
        calibration=MotorCalibration(
            ff=Feedforward(kS=0.11, kV=0.15768136518367729, kA=0.017155086054130467),
            pid=PidGains(kp=10.0, ki=10.0, kd=0.548293111922021),
            ticks_to_rad=0.004448910019230072,
            vel_lpf_alpha=0.8,
        ),
    )
    drum_motor = Motor(port=2, inverted=False)
    drum_light_sensor = AnalogSensor(port=1)
    drum_distance_sensor = ThresholdedSensor(port=0)
    drum_pusher_servo = Servo(port=0)
    front_left_ir_sensor = IRSensor(port=0)
    front_right_ir_sensor = IRSensor(port=1)
    analog_sensors = [
        drum_light_sensor,
        drum_distance_sensor,
        front_left_ir_sensor,
        front_right_ir_sensor,
    ]


__all__ = ["Defs"]
