"""
===========================================================
 Project:   tobi-test
 Generated: 2026-02-15 09:13:48
===========================================================

Authors:
  • Tobias Madlberger (Scaffold / CLI Author)
  • RaccoonOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.
"""

from libstp import (
    AxisVelocityControlConfig,
    ChassisVelocityControlConfig,
    Drive,
    Feedforward,
    FusedOdometry,
    FusedOdometryConfig,
    GenericRobot,
    MecanumKinematics,
    PidGains,
    SensorPosition,
    UnifiedMotionPidConfig,
    WheelPosition,
)

from src.hardware.defs import Defs


from src.missions.setup_mission import SetupMission
from src.missions.shutdown_mission import ShutdownMission
from src.missions.potato_mission import PotatoMission


def _build_chassis_vel_config(vx=None, vy=None, wz=None):
    cfg = ChassisVelocityControlConfig()
    if vx is not None:
        cfg.vx = vx
    if vy is not None:
        cfg.vy = vy
    if wz is not None:
        cfg.wz = wz
    return cfg


class Robot(GenericRobot):
    defs = Defs()
    kinematics = MecanumKinematics(
        back_left_motor=defs.rear_left_motor,
        back_right_motor=defs.rear_right_motor,
        front_left_motor=defs.front_left_motor,
        front_right_motor=defs.front_right_motor,
        track_width=0.19,
        wheel_radius=0.0295,
        wheelbase=0.12,
    )
    drive = Drive(
        kinematics=kinematics,
        vel_config=_build_chassis_vel_config(
            vx=AxisVelocityControlConfig(
                pid=PidGains(kp=0.0, ki=0.0, kd=0.0),
                ff=Feedforward(kS=0.0, kV=1.0, kA=0.0),
            ),
            vy=AxisVelocityControlConfig(
                pid=PidGains(kp=0.0, ki=0.0, kd=0.0),
                ff=Feedforward(kS=0.0, kV=1.0, kA=0.0),
            ),
            wz=AxisVelocityControlConfig(
                pid=PidGains(kp=0.65, ki=0.0, kd=0.0),
                ff=Feedforward(kS=0.0, kV=1.0, kA=0.0),
            ),
        ),
        imu=defs.imu,
    )
    odometry = FusedOdometry(
        imu=defs.imu, kinematics=kinematics, config=FusedOdometryConfig(bemf_trust=0.8)
    )
    motion_pid_config = UnifiedMotionPidConfig(
        velocity_ff=1.0,
        distance={"kp": 1.0, "ki": 0.0, "kd": 0.5, "tolerance_m": 0.005},
        heading={
            "kp": 1.0,
            "ki": 0.0,
            "kd": 0.2,
            "min_scale": 0.25,
            "saturation_error_rad": 0.01,
            "recovery_error_rad": 0.005,
        },
        lateral={
            "kp": 1.0,
            "ki": 0.0,
            "kd": 0.0,
            "heading_bias_gain": 0.5,
            "reorient_threshold_m": 0.15,
        },
        integral_max=10.0,
        integral_deadband=0.01,
        derivative_lpf_alpha=0.5,
        output_min=-10.0,
        output_max=10.0,
        saturation={
            "derating_factor": 0.85,
            "min_scale": 0.2,
            "recovery_rate": 0.02,
            "hold_cycles": 5,
            "recovery_threshold": 0.95,
        },
        heading_saturation={"derating_factor": 0.85},
        heading_recovery_rate=0.05,
        angle_tolerance_rad=0.017,
        reorientation_speed_factor=0.3,
        default_linear_acceleration_mps2=0.3333,
        default_linear_deceleration_mps2=0.6229,
        default_linear_max_velocity_mps=0.2153,
        default_lateral_acceleration_mps2=0.3922,
        default_lateral_deceleration_mps2=0.6504,
        default_lateral_max_velocity_mps=0.2145,
        default_angular_acceleration_radps2=1.8933,
        default_angular_deceleration_radps2=7.754,
        default_angular_max_rate_radps=1.5864,
    )
    missions = [PotatoMission()]
    setup_mission = SetupMission()
    shutdown_mission = ShutdownMission()
    width_cm = 13.0
    length_cm = 19.0
    rotation_center_forward_cm = -2.1715
    rotation_center_strafe_cm = 0.0
    _sensor_positions = {
        defs.front_left_ir_sensor: SensorPosition(
            forward_cm=7.5, strafe_cm=3.5, clearance_cm=1.0
        ),
        defs.front_right_ir_sensor: SensorPosition(
            forward_cm=7.5, strafe_cm=-3.3, clearance_cm=1.0
        ),
    }
    _wheel_positions = {
        defs.front_left_motor: WheelPosition(forward_cm=6.0, strafe_cm=9.5),
        defs.front_right_motor: WheelPosition(forward_cm=6.0, strafe_cm=-9.5),
        defs.rear_left_motor: WheelPosition(forward_cm=-6.0, strafe_cm=9.5),
        defs.rear_right_motor: WheelPosition(forward_cm=-6.0, strafe_cm=-9.5),
    }


__all__ = ["Robot"]
