"""Base generator class using the Template Method pattern."""

from __future__ import annotations

import logging
from abc import ABC, abstractmethod
from pathlib import Path
from typing import Any, Dict

from ..builder import ImportSet

logger = logging.getLogger("raccoon")


class BaseGenerator(ABC):
    """
    Abstract base class for code generators.

    Uses the Template Method pattern to define the generation workflow.
    Subclasses override specific steps to customize behavior.
    """

    def __init__(self, class_name: str = None):
        """
        Initialize the generator.

        Args:
            class_name: Optional class name for the generated code
        """
        self.class_name = class_name
        self.imports = ImportSet()

    @abstractmethod
    def get_output_filename(self) -> str:
        """Return the output filename for this generator."""
        pass

    @abstractmethod
    def extract_config(self, config: Dict[str, Any]) -> Dict[str, Any]:
        """
        Extract relevant configuration for this generator.

        Args:
            config: Full project configuration

        Returns:
            Extracted configuration subset
        """
        pass

    @abstractmethod
    def validate_config(self, data: Dict[str, Any]) -> None:
        """
        Validate the extracted configuration.

        Args:
            data: Configuration data to validate

        Raises:
            ValueError: If configuration is invalid
        """
        pass

    @abstractmethod
    def generate_body(self, data: Dict[str, Any]) -> str:
        """
        Generate the main body of the file.

        Args:
            data: Validated configuration data

        Returns:
            Generated code body
        """
        pass

    def generate_header(self) -> str:
        """Generate file header comment."""
        return "# This file was generated by raccoon codegen — do not edit by hand."

    def generate_imports(self) -> str:
        """Generate import statements."""
        return self.imports.render()

    def generate_footer(self) -> str:
        """Generate file footer (e.g., __all__ export)."""
        if self.class_name:
            return f"\n__all__ = ['{self.class_name}']\n"
        return ""

    def generate(self, config: Dict[str, Any]) -> str:
        """
        Template method that orchestrates the generation process.

        Args:
            config: Full project configuration

        Returns:
            Complete generated source code
        """
        logger.info(f"Generating {self.get_output_filename()}...")

        # Extract relevant config
        data = self.extract_config(config)
        logger.debug(f"Extracted config for {self.__class__.__name__}")

        # Validate
        self.validate_config(data)
        logger.debug(f"Validated config for {self.__class__.__name__}")

        # Generate components
        header = self.generate_header()
        body = self.generate_body(data)
        imports = self.generate_imports()
        footer = self.generate_footer()

        # Compose final source
        parts = [header]
        if imports:
            parts.append(imports)
        parts.append("")  # Blank line after imports
        parts.append(body)
        parts.append(footer)

        result = "\n".join(parts)
        logger.info(f"✓ Generated {self.get_output_filename()}")
        return result

    def write(self, config: Dict[str, Any], output_dir: Path, format_code: bool = True) -> Path:
        """
        Generate and write the file to disk.

        Args:
            config: Full project configuration
            output_dir: Directory to write output file
            format_code: Whether to format with black

        Returns:
            Path to written file
        """
        source = self.generate(config)

        # Format with black if requested and available
        if format_code:
            try:
                import black
                logger.debug(f"Formatting {self.get_output_filename()} with black...")
                source = black.format_str(source, mode=black.Mode(line_length=88))
            except ImportError:
                logger.warning("black not installed, skipping formatting")

        # Write to disk
        output_file = output_dir / self.get_output_filename()
        output_file.parent.mkdir(parents=True, exist_ok=True)
        output_file.write_text(source, encoding="utf-8")
        logger.debug(f"Wrote {output_file}")

        return output_file
