"""Main code generation logic."""

from __future__ import annotations

from typing import Any, Dict

from .introspection import resolve_class
from .builder import ImportSet, build_constructor_expr

# Root class for each definition entry. Keep this constant minimal.
ROOT_QUALNAME = "libstp.hal.Motor"


def generate_defs_source(config: Dict[str, Any], class_name: str = "Defs") -> str:
    """
    Build the Python source for defs.py from the config dictionary,
    inferring nested types & imports from annotations only.
    """
    Root = resolve_class(ROOT_QUALNAME)

    imports = ImportSet()
    fields = []

    definitions = config.get("definitions")
    if not isinstance(definitions, dict):
        raise SystemExit("Top-level config must be a mapping with key 'definitions:'")

    for field_name, motor_cfg in definitions.items():
        if not isinstance(motor_cfg, dict):
            raise ValueError(f"definitions.{field_name} must be a mapping")
        motor_expr = build_constructor_expr(Root, motor_cfg, f"definitions.{field_name}", imports)
        fields.append((field_name, motor_expr))

    # Compose final source
    lines = []
    lines.append("# This file was generated by raccoon codegen — do not edit by hand.")
    lines.append(imports.render())
    lines.append("")
    lines.append(f"class {class_name}:")
    if not fields:
        lines.append("    pass")
    else:
        for name, expr in fields:
            # ensure valid identifier (basic safeguard; keep your YAML keys sane)
            if not name.isidentifier():
                raise ValueError(f"definitions.{name}: not a valid Python identifier")
            lines.append(f"    {name} = {expr}")
    lines.append("")
    lines.append(f"__all__ = ['{class_name}']")
    lines.append("")
    return "\n".join(lines)
