"""Local git history helpers for project scaffolding.

Pre-sync safety snapshots live in :mod:`raccoon_cli.checkpoint`, which stores
them as invisible refs via ``git stash create`` rather than real commits.
"""

from __future__ import annotations

import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path

AUTO_GIT_USER_NAME = "Raccoon Auto History"
AUTO_GIT_USER_EMAIL = "raccoon@local"


@dataclass
class GitInitResult:
    """Result of project git initialization."""

    initialized: bool
    commit_created: bool
    commit_sha: str | None = None
    reason: str = ""
    error: str = ""


def _run_git(project_root: Path, args: list[str]) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", *args],
        cwd=project_root,
        capture_output=True,
        text=True,
    )


def is_git_available() -> bool:
    """Return True if git is available in PATH."""
    return shutil.which("git") is not None


def is_git_repo(project_root: Path) -> bool:
    """Return True if project_root is inside a git repository."""
    if not is_git_available():
        return False

    proc = _run_git(project_root, ["rev-parse", "--is-inside-work-tree"])
    return proc.returncode == 0 and proc.stdout.strip() == "true"


def _has_staged_changes(project_root: Path) -> tuple[bool, str]:
    """Return whether the index has staged changes."""
    proc = _run_git(project_root, ["diff", "--cached", "--quiet"])
    if proc.returncode == 1:
        return True, ""
    if proc.returncode == 0:
        return False, ""
    return False, proc.stderr.strip() or proc.stdout.strip()


def _commit(
    project_root: Path,
    subject: str,
    body: str | None = None,
) -> tuple[str | None, str]:
    args = [
        "-c",
        f"user.name={AUTO_GIT_USER_NAME}",
        "-c",
        f"user.email={AUTO_GIT_USER_EMAIL}",
        "-c",
        "commit.gpgsign=false",
        "commit",
        "--no-verify",
        "-m",
        subject,
    ]
    if body:
        args.extend(["-m", body])

    commit_proc = _run_git(project_root, args)
    if commit_proc.returncode != 0:
        return None, commit_proc.stderr.strip() or commit_proc.stdout.strip()

    sha_proc = _run_git(project_root, ["rev-parse", "--short", "HEAD"])
    if sha_proc.returncode != 0:
        return None, sha_proc.stderr.strip() or sha_proc.stdout.strip()

    return sha_proc.stdout.strip(), ""


def initialize_project_history(project_root: Path, project_name: str) -> GitInitResult:
    """Initialize a local git repository and create an initial scaffold commit."""
    if not is_git_available():
        return GitInitResult(initialized=False, commit_created=False, reason="git_unavailable")

    if is_git_repo(project_root):
        return GitInitResult(initialized=False, commit_created=False, reason="already_git_repo")

    init_proc = _run_git(project_root, ["init", "--initial-branch", "main"])
    if init_proc.returncode != 0:
        init_proc = _run_git(project_root, ["init"])
        if init_proc.returncode != 0:
            return GitInitResult(
                initialized=False,
                commit_created=False,
                reason="init_failed",
                error=init_proc.stderr.strip() or init_proc.stdout.strip(),
            )

    add_proc = _run_git(project_root, ["add", "-A"])
    if add_proc.returncode != 0:
        return GitInitResult(
            initialized=True,
            commit_created=False,
            reason="add_failed",
            error=add_proc.stderr.strip() or add_proc.stdout.strip(),
        )

    has_changes, check_error = _has_staged_changes(project_root)
    if check_error:
        return GitInitResult(
            initialized=True,
            commit_created=False,
            reason="status_failed",
            error=check_error,
        )

    if not has_changes:
        return GitInitResult(initialized=True, commit_created=False, reason="no_changes")

    subject = f"chore(project): scaffold {project_name}"
    body = "Initial project scaffold generated by `raccoon create project`."
    commit_sha, commit_error = _commit(project_root, subject, body=body)
    if commit_error:
        return GitInitResult(
            initialized=True,
            commit_created=False,
            reason="commit_failed",
            error=commit_error,
        )

    return GitInitResult(
        initialized=True,
        commit_created=True,
        commit_sha=commit_sha,
    )
