from .missions.setup_mission import SetupMission
from .missions.shutdown_mission import ShutdownMission
"""
===========================================================
 Project:   SensorCalibration
 Generated: 2026-01-15 08:43:57
 Tool:      Raccoon IDE
 Platform:  StpOS – Robotics Operating System
===========================================================

Authors:
  • Tobias Madlberger (Scaffold Author)
  • StpOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.

Note: This header credits the scaffold and tooling only - no copyright is
claimed over the generated code itself.
"""

from src.hardware.robot import Robot
from libstp.button import set_digital
import libstp.foundation as logging

robot = Robot()

logging.set_global_level(logging.Level.info)

if __name__ == "__main__":
   set_digital(10)
   robot.start()