"""
===========================================================
 Project:   Example Project
 Generated: 2025-12-11 08:42:56
===========================================================

Authors:
  • Tobias Madlberger (Scaffold / CLI Author)
  • RaccoonOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.
"""

from libstp.foundation import Feedforward, MotorCalibration, PidGains
from libstp.hal import DigitalSensor, Motor, Servo
from libstp.hal import IMU as Imu


class Defs:
    imu = Imu()
    front_left_motor = Motor(
        port=0,
        inverted=False,
        calibration=MotorCalibration(
            ff=Feedforward(kS=0.08, kV=0.12, kA=0.1),
            pid=PidGains(kp=2.4, ki=0.3, kd=0.08),
            ticks_to_rad=0.00418879,
            vel_lpf_alpha=0.8,
        ),
    )
    rear_left_motor = Motor(
        port=2,
        inverted=False,
        calibration=MotorCalibration(
            ff=Feedforward(kS=0.08, kV=0.12, kA=0.1),
            pid=PidGains(kp=2.4, ki=0.3, kd=0.08),
            ticks_to_rad=0.00418879,
            vel_lpf_alpha=0.8,
        ),
    )
    front_right_motor = Motor(
        port=1,
        inverted=False,
        calibration=MotorCalibration(
            ff=Feedforward(kS=0.08, kV=0.12, kA=0.1),
            pid=PidGains(kp=2.4, ki=0.3, kd=0.08),
            ticks_to_rad=0.00418879,
            vel_lpf_alpha=0.8,
        ),
    )
    rear_right_motor = Motor(
        port=3,
        inverted=False,
        calibration=MotorCalibration(
            ff=Feedforward(kS=0.08, kV=0.12, kA=0.1),
            pid=PidGains(kp=2.4, ki=0.3, kd=0.08),
            ticks_to_rad=0.00418879,
            vel_lpf_alpha=0.8,
        ),
    )
    button = DigitalSensor(port=10)
    potato_server = Servo(port=0)


__all__ = ["Defs"]
