"""
===========================================================
 Project:   Example Project
 Generated: 2025-11-09 12:36:04
===========================================================

Authors:
  • Tobias Madlberger (Scaffold / CLI Author)
  • RaccoonOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.
"""

from libstp.drive import Drive
from libstp.kinematics_mecanum import MecanumKinematics
from libstp.odometry_fused import FusedOdometry

from libstp.robot.api import GenericRobot

from src.hardware.defs import Defs
from src.missions.drive_to_potato_mission import DriveToPotatoMission


class Robot(GenericRobot):
    defs = Defs()
    kinematics = MecanumKinematics(
        back_left_motor=defs.rear_left_motor,
        back_right_motor=defs.rear_right_motor,
        front_left_motor=defs.front_left_motor,
        front_right_motor=defs.front_right_motor,
        track_width=0.19,
        wheel_radius=0.03,
        wheelbase=0.12,
    )
    drive = Drive(
        kinematics=kinematics,
    )
    odometry = FusedOdometry(
        imu=defs.imu,
        kinematics=kinematics,
    )
    missions = [
        DriveToPotatoMission(),
    ]


__all__ = ["Robot"]
