"""
===========================================================
 Project:   remote-example
 Generated: 2026-01-02 16:54:39
===========================================================

Authors:
  • Tobias Madlberger (Scaffold / CLI Author)
  • RaccoonOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.
"""

from libstp.hal import AnalogSensor
from libstp.hal import IMU as Imu


class Defs:
    imu = Imu()
    button = AnalogSensor(port=10)


__all__ = ["Defs"]
