"""
===========================================================
 Project:   remote-example
 Generated: 2026-01-02 16:54:41
===========================================================

Authors:
  • Tobias Madlberger (Scaffold / CLI Author)
  • RaccoonOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.
"""

from libstp.drive import Drive, MotionLimits
from libstp.kinematics_mecanum import MecanumKinematics
from libstp.motion import UnifiedMotionPidConfig
from libstp.odometry_fused import FusedOdometry

from libstp.robot.api import GenericRobot

from src.hardware.defs import Defs


class Robot(GenericRobot):
    defs = Defs()
    kinematics = MecanumKinematics(
        back_left_motor=defs.rear_left_motor,
        back_right_motor=defs.rear_right_motor,
        front_left_motor=defs.front_left_motor,
        front_right_motor=defs.front_right_motor,
        max_acceleration=240.0,
        max_velocity=40.0,
        track_width=0.19,
        wheel_radius=0.03,
        wheelbase=0.12,
    )
    drive = Drive(
        kinematics=kinematics, chassis_lim=MotionLimits(max_omega=10.0, max_v=2.0)
    )
    odometry = FusedOdometry(imu=defs.imu, kinematics=kinematics)
    motion_pid_config = UnifiedMotionPidConfig(
        derivative_lpf_alpha=0.1,
        distance_kd=0.0,
        distance_ki=0.0,
        distance_kp=2.0,
        heading_kd=0.0,
        heading_ki=0.0,
        heading_kp=3.0,
        heading_saturation_derating_factor=0.85,
        heading_saturation_min_scale=0.25,
        heading_saturation_recovery_rate=0.05,
        integral_deadband=0.01,
        integral_max=10.0,
        lateral_heading_bias_gain=0.5,
        lateral_heading_recovery_error_rad=0.005,
        lateral_heading_saturation_error_rad=0.01,
        lateral_kd=0.0,
        lateral_ki=0.0,
        lateral_kp=2.0,
        lateral_reorient_threshold_m=0.15,
        max_angular_acceleration=3.0,
        max_heading_rate=3.0,
        max_linear_acceleration=1.0,
        min_angular_rate=0.1,
        min_speed_mps=0.05,
        output_max=10.0,
        output_min=-10.0,
        saturation_derating_factor=0.85,
        saturation_min_scale=0.1,
        saturation_recovery_rate=0.02,
        tolerance_angle_rad=0.02,
        tolerance_distance_m=0.01,
    )


__all__ = ["Robot"]
