from .missions.setup_mission import SetupMission
from .missions.shutdown_mission import ShutdownMission
from .missions.new_test_mission import NewTestMission

"""
===========================================================
 Project:   Sample Project
 Generated: 2025-08-19 00:51:46
 Tool:      Raccoon IDE
 Platform:  StpOS – Robotics Operating System
===========================================================

Authors:
  • Tobias Madlberger (Scaffold Author)
  • StpOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.

Note: This header credits the scaffold and tooling only - no copyright is
claimed over the generated code itself.
"""

robot = Robot(config="config.yaml")

# --- Missions that will be used in a run ---
robot.use_missions(
    DriveToPotato(),
NewTestMission())

robot.set_setup_mission(SetupMission())
robot.set_shutdown_mission(ShutdownMission())

if __name__ == "__main__":
    robot.start()
