# This file was generated by raccoon codegen — do not edit by hand.
from libstp.foundation import Deadzone, Feedforward, MotorCalibration, PidGains
from libstp.hal import Motor
from src.hardware.custom_servo import CustomServo


class Defs:
    left_motor = Motor(
        port=0,
        inverted=False,
        calibration=MotorCalibration(
            ff=Feedforward(kS=0.1, kV=0.05, kA=0.01),
            pid=PidGains(kp=1.0, ki=0.1, kd=0.05),
            deadzone=Deadzone(
                enable=True,
                zero_window_percent=2.0,
                start_percent=5.0,
                release_percent=3.0,
            ),
            max_percent_output=100.0,
            ticks_to_rad=0.001534,
            vel_lpf_alpha=0.8,
        ),
    )
    right_motor = Motor(
        port=0,
        inverted=False,
        calibration=MotorCalibration(
            ff=Feedforward(kS=0.1, kV=0.05, kA=0.01),
            pid=PidGains(kp=1.0, ki=0.1, kd=0.05),
            deadzone=Deadzone(
                enable=True,
                zero_window_percent=2.0,
                start_percent=5.0,
                release_percent=3.0,
            ),
            max_percent_output=100.0,
            ticks_to_rad=0.001534,
            vel_lpf_alpha=0.8,
        ),
    )
    potato_arm_servo = CustomServo(port=0)


__all__ = ["Defs"]
