# This file was generated by raccoon codegen — do not edit by hand.
from libstp.drive import Drive, MotionLimits
from libstp.kinematics_differential import DifferentialKinematics

from src.hardware.defs import Defs


class Robot:
    kinematics = DifferentialKinematics(
        left_motor=Defs.left_motor,
        max_acceleration=3.0,
        max_velocity=2.0,
        right_motor=Defs.right_motor,
        wheel_radius=0.07,
        wheelbase=0.15,
    )
    drive = Drive(
        kinematics=kinematics, chassis_lim=MotionLimits(max_omega=8.0, max_v=2.0)
    )


__all__ = ["Robot"]
