"""
===========================================================
 Project:   Example Project
 Generated: 2025-10-16 08:44:22
===========================================================

Authors:
  • Tobias Madlberger (Scaffold / CLI Author)
  • RaccoonOS Development Team (Contributors)

⚠️ This file was auto-generated by the project scaffold template.
   You are free to modify it as needed. Regeneration may overwrite changes.
"""

from libstp.drive import Drive, MotionLimits
from libstp.kinematics_mecanum import MecanumKinematics

from libstp.robot.api import GenericRobot

from src.hardware.defs import Defs


class Robot(GenericRobot):
    defs = Defs()
    kinematics = MecanumKinematics(
        back_left_motor=defs.rear_left_motor,
        back_right_motor=defs.rear_right_motor,
        front_left_motor=defs.front_left_motor,
        front_right_motor=defs.front_right_motor,
        max_acceleration=3.0,
        max_velocity=2.0,
        track_width=0.2,
        wheel_radius=0.0375,
        wheelbase=0.15,
    )
    drive = Drive(
        kinematics=kinematics, chassis_lim=MotionLimits(max_omega=8.0, max_v=2.0)
    )


__all__ = ["Robot"]
